import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-screen bg-gradient-to-b from-indigo-600 to-indigo-400">
                <h1 className="text-indigo-500">Hello word</h1>
                <h2>Hehe</h2>
            </div>
        </div>
    );
};

export default Home;
