import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import React, { useState } from "react";
import { useRouter } from "next/router";
interface IAppProps {
    post: Post[];
}
type Post = {
    title: string;
    text: string;
};
const Home: NextPage<IAppProps> = ({ post }) => {
    const router = useRouter();
    const [newPost, setNewPost] = useState<Post>({
        title: "",
        text: "",
    });
    const onChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = e.target;
        setNewPost({
            ...newPost,
            [name]: value,
        });
    };
    const addPost = (e: React.SyntheticEvent) => {
        e.preventDefault();
        axios.post("http://localhost:3000/api/post", newPost);
        setNewPost({
            title: "",
            text: "",
        });
        router.push("/");
    };
    return (
        <div className={styles.container}>
            <Head>
                <title>Post next-js</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="h-screen bg-gradient-to-b from-indigo-600 to-indigo-400 flex ">
                <div className="w-6/12 p-4 h-screen border-r-2 border-cyan-300">
                    <div className="text-white font-normal text-2xl ">
                        Tạo bài viết mới
                    </div>
                    <div>
                        <form>
                            <div className="flex flex-col">
                                <div className="w-1/2 mt-6">
                                    <label className="text-white">
                                        Tiêu đề
                                    </label>
                                    <input
                                        className="w-full rounded-md p-1"
                                        type="text"
                                        placeholder="Tiêu đề"
                                        value={newPost.title}
                                        name="title"
                                        onChange={onChange}
                                    />
                                </div>
                                <div className="w-1/2 mt-6">
                                    <label className="text-white">
                                        Nội dung
                                    </label>
                                    <input
                                        className="w-full rounded-md p-1"
                                        type="text"
                                        placeholder="Nội dung"
                                        name="text"
                                        value={newPost.text}
                                        onChange={onChange}
                                    />
                                </div>
                                <div className="w-1/2 mt-6">
                                    <button
                                        className="p-2  text-white font-medium bg-green-500 rounded-lg"
                                        onClick={addPost}
                                    >
                                        Thêm
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div className="flex flex-col w-6/12 p-4 h-screen ">
                    <div className="text-white font-normal text-2xl ">
                        Danh sách bài viết
                    </div>
                    <div className="flex flex-wrap overflow-y-scroll justify-center">
                        {post.map((item) => (
                            <div className="p-4 w-full h-64 rounded-lg backdrop-blur-md bg-white/30 mx-2 my-1">
                                <h1 className="text-2xl font-bold">
                                    {item.title}
                                </h1>
                                <p className="text-xl">{item.text}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
};
export async function getServerSideProps() {
    const res = await axios.get("http://localhost:3000/api/post");
    const data = await res.data;
    console.log(data);
    return {
        props: {
            post: data,
        },
    };
}
export default Home;
